### ISSUE TITLE
Transaction tab filter by date

### ISSUE THREAD

**Issue by yvgithub** [ucoin-io/sakia#115]
The same filter by date range for transaction give me inconsistent result from day to day.

yesterday screenshot
![transactionbydate](https://cloud.githubusercontent.com/assets/1395647/7374515/ca2ad552-eda0-11e4-9381-5a6bed151196.png)

today screenshot
![disparitiondetransaction](https://cloud.githubusercontent.com/assets/1395647/7374392/16dda9fc-eda0-11e4-85fb-decb815ba595.png)

**Comment by Insoleet** [comment]
This is really weird. Do you have any more informations ? Did the network disconnect, did you do anything between these two filters ?

**Comment by yvgithub** [comment]
Did the network disconnect? -> I don't know
Did you do anything between these two filters? ->
Nothing special 
Open cutecoin on 27-04-2015 play with the new version, add contact and use the filter by date. Take a screenshot. Close cutecoin.
The next day (28-04-215) open cutecoin use filter by date play a little bit with it using different date. My goal was to take a new screenshot to illustrate the diff in the fuzzy boundary bug.
The rest is history...

**Comment by Insoleet** [comment]
Ok. Weird. 

Canno't reproduce at the moment, waiting for more informations...
