### ISSUE TITLE
Add a mode to see amounts in UD at the time of the transaction

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/sakia#130]
When I have made a transaction of 1 UD, as time goes by, it decrease because current UD is bigger than the 1 UD at the time of the transaction.

It would be usefull to show amounts in UD "at the time of the transaction", beside the actual mode of showing in "current UD".

**Comment by Insoleet** [comment]
That'd be a great enhancement.
This referential need some changes in the current way the referentials work. 
I suggest to implement it after the global refactoring for the 0.11. Implementing more complex referentials needs to be thought.

**Comment by M5oul** [comment]
I suggest to add an other column `DU at time of transaction` next to the DU column in the transaction tab.

**Comment by Insoleet** [comment]
Implemented in branch `feature/past_dividend` . Please check it out and tell me what you think about it ! :)

**Comment by M5oul** [comment]
It's great!
