### ISSUE TITLE
Asking for "Add an account" button

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#142]
It's hard to add an existing account on CuteCoin when it is empty of configuration.
First, I try `Import an account` thinking it means `add an account`.
Then, I go create an account, put my uid, my salt, my password. Ok, for that part.
Then, I add the node, I need to clic many time ok, then enter one more time my password :(
Finaly, there should be a button `Add an account`

**Comment by Insoleet** [comment]
We should change account management to have one like ucoin-apps, it's more userfriendly : 
- Create an account should create an account and check that UID is available + publish it
- Connect to an account should check that the UID was already published
