### ISSUE TITLE
Display little UD amounts in a more friendly way (0,001 UD => 1mUD)

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/sakia#188]
Add a config parameters to display little UD amounts in a friendly way : 

0,001 UD => 1 mUD
0,01 UD => 1 cUD
0,1 UD => 1 dUD

may be those units needs to be translated...

**Comment by M5oul** [comment]
Great idea :smile:

**Comment by Insoleet** [comment]
I changed the referentials API : 
https://github.com/ucoin-io/cutecoin/commit/da58e28e46fc2556aa363633527f16a3d5075e7a

Should be more easy to implements such features when we need ;) .

**Comment by Insoleet** [comment]
Please check out my proposal and see if it corresponds to what we need.

We should add a parameter in the display section, to enable or not the scientific notation.

**Comment by scith** [comment]
Hi, I think this is a good idea but it should be implemented in a less radical way...
For example in my transaction I see:
*1.000 UD* and *9.091 dUD*

I would prefer to see *1.000 UD* and *0.909 UD* which I find less complex.
I think there needs to be a balance between the scientific notation and the international one.

For example for Litres we often use hL, L, cL and mL but very rarely use daL and dL ... There is no need to use all notations thanks to digit rounding.

Thanks

**Comment by Insoleet** [comment]
So which units should we display ?

**Comment by scith** [comment]
Hmm I'm not sure, any idea?
At least not dUD

**Comment by M5oul** [comment]
kUD, UD, mUD, μUD, nUD?

**Comment by Arcurus** [comment]
I suggest:
0,001 UD => 1 mUD
1 UD => 1 UD

the switch to dUDs is very confusing.
even better would be to display UD in UD per day (%) for example 100 UDD (UD per day).
in this case we would not need much units below 0.

**Comment by galuel** [comment]
dUD, cUD, mUD are not standard ways to scale numbers. A correct scale number (international normalisation) is 10⁻¹,10-²,10⁻³ etc.

So a correct way to propose a scale should be to put the power number in preferences and to put informations at the top of transactions, in the same line than the dates, and avoid to put "UD" unit in the tabs (as it will be noted on that top line).

Line : Date begin, Date end, Money Name, Referential (Q,UD,QZ,RZ...), Unit Power (10⁻¹,10-²,10⁻³...)

**Comment by Insoleet** [comment]
I'm not sure that 10⁻¹,10-²,10⁻³ would be really user friendly. I never this in front of money units. It's probably standard, but not common in daily life. I'd prefer to go for the proposal to remove centi and deci units.

**Comment by Arcurus** [comment]
In the current use of money only ¨cents¨ are common. Scientific notation is more for scientific use not for people who use money.
Therefore I change my suggestions to use:  
0,01 UD => 1 cUD
If by default we display the UD in 100 UDUnits per day, then we would not have to use much numbers below 0.

**Comment by scith** [comment]
I agree that we should stick to the language people already use for currency.
1 cUD might be relevant but then 0,01 UD is not hard to read/understand and people are used to 10^-2 because of price tags. The problem is that currency language is mixing scientific and non-scientific notation... (eg we say k€ for thousands but not for kilo, and million instead of mega for millions...): https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes

I prefer your suggestion of UD, mUD. Perhaps we could have:
kUD => 1,000
UD
mUD => 0,001

But then what if we need to go higher or lower? Higher we could have million (MUD), billion (BnUD) which are understandable in terms of currency language. But what about lower?

**Comment by Arcurus** [comment]
maybe we dont need at all kUDs mUD and so on if the default unit is one Unit = 1% of UD per day.
in this case for normal use we will not get much below 0 (we dont have the bitcoin problem :))
above 0 is easy to read for  humans: 1.000 or even 1.000.000 is still ok to display, humans love big numbers :) in average one participant will have 100*30*12*10 cUDD  = 360.000 cUDD thats still ok to display :)

**Comment by vtexier** [comment]
Don't mix display form and units. With mUD, cUD the display change, not the unit/referential.
If your display needs a transform formula on the value before display, it is a new unit, so a new referential.

@Arcurus : I suggest you to create a new referential for UDD.

Please give us the following informations :

Name: Name of the referential in the selector.
Units: text displayed after values.
Formula: Formula to transform the internal value in the new referential.
Description: An explanation of what is this referential and his purpose.

With enough informations, a new referential can be created and explain to users.
So I can select the UD referential (which I prefer), or select UDD when I please.

**Comment by Arcurus** [comment]
Name: Mango (Universal dividend per day in percent / Mango is just a replacement until we have a nice name :) )
Units: Mango
Formula: 1 Mango  = Units * 100 / (UD of one day ) )
Description:   Universal Dividend per Day displayed in percent. The purpose is to have a default unit that is easy to use and understand. 100 Mangos equal the universal dividend received per member per day.

**Comment by vtexier** [comment]
Thanks @arcurus ! I will implement your new referential asap, if @Insoleet is ok.

**Comment by Insoleet** [comment]
I think it's okay. But this won't have any sense probably with Meta_brouzouf since we are already generating UD every day...

**Comment by Arcurus** [comment]
much thx @vtexier 

lol yea for meta_bounzouf it would be nearly the same, just multiplied 100   :)
but for the beta currency it would be different :)
also because it is multiplied by 100  we wont need much thinking about how to display small units properly ;) 
in true with meta_bounzouf with simulation one day one year we would have to multiply it with 36500 :)

**Comment by vtexier** [comment]
@Arcurus : 
I've done it in the dev branch !

Sorry for the name Mango, but you mentioned "UDD" and "Dividend per day", which I found more explicit, so I used it.
I have received 461,17 mUD from a member in UD Referential today.
It appears as 46,12 UDD in Dividend per day Referential.
Monetary mass and average per member are as Relative Referential but multiplied by 100.

Is it what you expected ?

**Comment by Arcurus** [comment]
yea UDD is fine :) 
if its correct i dont know, i must see the formula:

Formula: 1 UDD = Units * 100 / (**UD of one day** ) )

really correct it would be if the UDD amount of the  transactions is counted in the UD per Day of the time of the transaction. the account balance on the other hand is always counted with the current UD per day.

**Comment by Insoleet** [comment]
The code to compute the referential is the following : 

```python
        dividend = await self.community.dividend()
        params = await self.community.parameters()
        if dividend > 0:
            return (self.amount * 100) / (float(dividend) / (params['dt'] / 86400))
        else:
            return self.amount
```

It looks ok to me.

**Comment by vtexier** [comment]
It is ok, but as @Arcurus pointed out : 

> really correct it would be if the UDD amount of the transactions is counted in the UD per Day of the time of the transaction. 

So we have a big problem here.

Sakia should have a "forget Mode" as in ucoin apps to display transaction values at the time of the transaction.

So it should be a configurable mode of display, not a separate referential, which it is now with "pastUD".

It should apply to all "Relative to UD" referentials.

Quite some work here...

**Comment by Arcurus** [comment]
¨It should apply to all "Relative to UD" referentials.¨
that would be great. that should be the default for relative units.
we ¨just¨ need a function who can get the amount of UD at time t. it should not be too difficult to extract that from the headers of the blockchain or?¨

**Comment by Insoleet** [comment]
@vtexier : Actually it's quite easy to implement and it's a good idea. We need a toggle in Display parameters of sakia to enable "forget Mode". Then, all relative referentials could check this parameter to choose what to display. It's easy since referentials have an access to the Application instance : https://github.com/ucoin-io/sakia/blob/dev/src/sakia/core/money/base_referential.py#L9

**Comment by Insoleet** [comment]
Done !
