### ISSUE TITLE
Build for Mac OS

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#189]
CuteCoin need to be multiplateform: GNU/Linux, Windows and Mac OS.

I could try to build a version at school with your help @Insoleet and @vtexier.

**Comment by vtexier** [comment]
To build binaries for mac os, we need to have a working developer install on mac, then try to use c_freeze...

You can start here : http://robscurity.blogspot.fr/2015/02/installing-pyqt-on-mac-os-x-yosemite.html

**Comment by M5oul** [comment]
@Insoleet, where could I find the forking repo for Mac OS? I have found that https://github.com/ucoin-io/cutecoin/network.

**Comment by Insoleet** [comment]
Here : https://github.com/MartinDelille/cutecoin/tree/patch-1

**Comment by couillardcharles** [comment]
Hi, i'll work on the Mac Os build this week end. Should i work on the dev branch or on the master?

**Comment by Insoleet** [comment]
The dev one :) Thanks !
