### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#202]
Python3 displayed 2.3 Gio of memory leak.

**Comment by M5oul** [comment]
I think it is due to the fact that I use two accounts.

**Comment by Insoleet** [comment]
Which version?

**Comment by M5oul** [comment]
On dev version.

**Comment by Insoleet** [comment]
Ok I'll look into this after the UI refactoring.

**Comment by Insoleet** [comment]
You can try the behavior now.

https://github.com/ucoin-io/cutecoin/commit/bc20b773150c8d2128de5537aef25f10d5d827fe

**Comment by M5oul** [comment]
After 3-4 hours running, I get 780 Mo of RAM:
![cutecoin_ram](https://cloud.githubusercontent.com/assets/4758871/11074740/8e2506a4-87f1-11e5-8964-823650c8612b.png)

**Comment by Insoleet** [comment]
Is it fixed ?

**Comment by M5oul** [comment]
Yep, it's better. Almost 130 Mo.
