### ISSUE TITLE
Similar identities should be differenciated using datetime field

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#211]
I had the following result looking for `paidge`:

![image](https://cloud.githubusercontent.com/assets/969136/9910892/adcfdd9e-5c9f-11e5-80e4-3c595da8d5d0.png)

That's a normal result, since paidge made 2 identities with the same keyring/userid but twice, thus not at the same time. We can see this at http://metab.ucoin.io/wot/lookup/paidge :

![image](https://cloud.githubusercontent.com/assets/969136/9910942/f19072a0-5c9f-11e5-91a6-4cf0fb9dc8ba.png)

To really see the difference between the two keys which are *really different identities* from UCP point of view, cutecoin should add a "made on" datetime column.

**Comment by Insoleet** [comment]
The current behaviour of cutecoin is : display only the last identity issued.

This problem only happens in searches because we are displaying the raw result of a lookup request.

Should cutecoin behaviour change ?

**Comment by c-geek** [comment]
Yes, cutecoin should definitely help users identity the good identity among others.

**Comment by Insoleet** [comment]
If an identity is defined by :  
- The UID
- The Pubkey
- The date of signature

BMA is missing something. I don't see in the requests "certifiers-of", "certified-by", "tx/history/[pubkey]" how we can check the date of the signature of the identity. Is there something I do not understand there ?

**Comment by c-geek** [comment]
You are right, API is missing the

```js
meta: {
    timestamp: 1421787800
}
```
next to `pubkey` and `uid` for exactitude. This is also true for http://metab.ucoin.io/wot/members.

**Comment by c-geek** [comment]
I've added an issue in uCoin: https://github.com/ucoin-io/ucoin/issues/161

**Comment by Insoleet** [comment]
There is something that I do not understand.

https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#transaction

A transaction uses only a pubkey as a source. Which identity's pubkey will it be ?
Can an UID be a double member, with 2 different timestamps ?

**Comment by c-geek** [comment]
Yes a transaction only refers a pubkey as source (I presume you say this for UD), and we could also use the UID instead because UCP defines a rule that both `uid` and `pubkey` unique **for a member**:

https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#identity

i.e. once a uid/pubkey has been written in the blockchain, the same uid cannot be used again. So does a pubkey. That's why we can indifferently use `uid` or `pubkey` as parameter of `certified-by` and `certifiers-of`, which are methods that search in *members* database:

* [/certified-by/inso](http://metab.ucoin.io/wot/certified-by/inso)
* [/certified-by/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU](http://metab.ucoin.io/wot/certified-by/8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU)

That's why if you try with the uid "sometest", which is not a member but a published valid identity, `certified-by` and `certifiers-of` will result in an error:

* [/certifiers-of/sometest](http://metab.ucoin.io/wot/certifiers-of/sometest)
* [/lookup/sometest](http://metab.ucoin.io/wot/lookup/sometest)

So to your last question: **no**, an UID cannot be a double member, neither can a pubkey.

**Comment by Insoleet** [comment]
So there is only one valid UID at a time ? Shouldn't we display only the last UID registered ?

**Comment by c-geek** [comment]
Yes we can, once the given identity is has become a member :smile:

**Comment by Insoleet** [comment]
Ow OK. That's why you want to display timestamps, because of identities in the pool...

**Comment by Insoleet** [comment]
How do i know which uid/timestamp will be written in the blockchain ? How do I know which selfcert was used for certifications ?
If the UID is present multiple times in the lookup, couldn't we simply use the latest one ?

**Comment by c-geek** [comment]
I will add a method for identity determinism.

Also, nodes reject new identities *once one identity with a shared UID/pubkey has been written*. But while pubkey/UID are not reserved because not written yet, we have great chances to have conflicts.

We might think about a single individual publishing several times the same pubkey/UID (with different timestamps), but we could also think about 2 individuals conflicting at the same time on a same UID. That's really possible, it's going to happen. Lots of JohnSnow for example :-)
