### ISSUE TITLE
Identity search when sending money and certify identity actions.

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#228]
As build actually in Cutecoin, we should deal with people which are in our contact list. Normal thing, because we mainly deal with people we know. But, it could be more user-friendly if we could search in all identities for this two actions. What do you think?

**Comment by Insoleet** [comment]
Like a search filter "Contacts" ?

**Comment by M5oul** [comment]
Yep, it could be a search filter in the contact list. But, I were thinking about search filter in all identity like on WoT and search identities tabs. I am not sure if it is useful. We will see that later.

**Comment by Insoleet** [comment]
I'm not sure to understand what you are trying to explain...

**Comment by M5oul** [comment]
I mean, searching for identities among all identities for sending money and certify identities actions.

**Comment by Insoleet** [comment]
Ah the dialogs which are at the moment suggesting to send to a contact, you think we should add a
search field ?

**Comment by M5oul** [comment]
Yep, it could be great.

**Comment by Insoleet** [comment]
Done https://github.com/ucoin-io/sakia/commit/55fa2e53f01382c71666da3e17f3453434250edf
