### ISSUE TITLE
Network tab

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#275]
![cutecoin_network](https://cloud.githubusercontent.com/assets/4758871/11530975/77a38bc6-98f9-11e5-83aa-dd1122cc8101.png)

Sometimes, my node moul.re without the identity (the green bottom one) appear then disappear. I don't know why.

Offline nodes should have disappear since a while.

**Comment by Insoleet** [comment]
I have the same problem. I wonder if this node is returned by the network somehow ?

**Comment by Insoleet** [comment]
Ok it seems to be a problem with ucoin nodes. These offlines keep being returned by the peering url : 
http://metab.ucoin.io/network/peering/peers?leaf=D0A18F9DBF6893958ABE8A4EF24196ACBF4B9437
http://metab.ucoin.io/network/peering/peers?leaf=1AD08A12EF8B2396C3321C7A3170E9EBD2AD93BF
http://metab.ucoin.io/network/peering/peers?leaf=C8416BA87EB872F2747B0E104B5C12CE93E06647

Is there any expiration on peering documents @c-geek ?

**Comment by c-geek** [comment]
No expiration at all. However, maybe `/peering/peers` should stop returning peers that are considered down by the node.

It currently returns all peers ever known.

**Comment by c-geek** [comment]
Well no I am wrong, it does return only UP peers. There might be a bug in the algorithm considering a node is UP or DOWN.
