### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#280]
On dev branch, I can't launch sakia:
```bash
  File "src/sakia/main.py", line 16, in <module>
    from sakia.gui.mainwindow import MainWindow
  File "/home/moul/projects/sakia/build/src/sakia/gui/mainwindow.py", line 98
    async def open_add_account_dialog(self, checked=False):
        ^
SyntaxError: invalid syntax
```

**Comment by Insoleet** [comment]
Yes I migrated to python 3.5. You'll have to upgrade your environment : 
You sould remove your current virtual env `pyenv uninstall [cutecoin-env]`

And then you should redo the steps to prepare your environment, as updated in the wiki for python 3.5.0 https://github.com/ucoin-io/sakia/wiki/Sakia-install-for-developpers

**Comment by M5oul** [comment]
Ok, I reinstall all my dev env, but:
```bash
  File "src/sakia/main.py", line 14, in <module>
    from quamash import QEventLoop
ImportError: No module named 'quamash'
```

I tried install it with:
```bash
pip install quamash
pip install -r requirement.txt
pyenv rehash
```

**Comment by Insoleet** [comment]
You probably missed something here. Can you show me your full console logs?

**Comment by M5oul** [comment]
Which logs do you mean? Dev env installation? Sakia lauching?

**Comment by Insoleet** [comment]
Dev env installation (the pip install quamash part, please check that you are in the pyenv virtualenv)

**Comment by M5oul** [comment]
I reinstall all in a new dev env:
[Logs not very explicit](https://moul.re/zerobin/?81461bd4a431f95d#4VorJWtCEzfh0tbKhgtgAXXI80TbhIdYULQpKnG8cmI=) which mainly contain PyQt compilation.

**Comment by Insoleet** [comment]
Well, the problem seems to be quamash, not PyQt, so why do you share PyQt logs ?

**Comment by M5oul** [comment]
Sorry, I found the solution. I will edit the wiki.

**Comment by Insoleet** [comment]
:+1:
