### ISSUE TITLE
No logo displayed since Sakia renaming

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#282]

**Comment by Insoleet** [comment]
Can you add a screenshot please ? Because on Windosw, the binary has a logo...

**Comment by M5oul** [comment]
I [can't right now](https://github.com/ucoin-io/sakia/issues/280).

**Comment by M5oul** [comment]
![capture d ecran de 2015-12-08 09-28-04](https://cloud.githubusercontent.com/assets/4758871/11651071/3f92ed46-9d8e-11e5-988a-2c440345253d.png)

**Comment by M5oul** [comment]
Fixed.
