### ISSUE TITLE
allow copy/paste to clipboard

### ISSUE THREAD

**Issue by Sylvain303** [ucoin-io/sakia#287]
Allow some right-click submenu to copy json block in txt format to the clipboard.

So for debuging purpose you can copy/paste for example in transaction  tab to obtain full data and exchange with other user by xmpp or in issue, or what ever.

For example to get the blockchain transaction id of an send money transaction.

**Comment by Insoleet** [comment]
On the go on branch feature/copy_documents .

@vtexier : I created a new generic class to create the same menus everywhere in the application. Just so you know... https://github.com/ucoin-io/sakia/blob/feature/copy_documents/src/sakia/gui/widgets/context_menu.py

**Comment by vtexier** [comment]
Great job !
And I notice that your doc-strings are now fully completed to allow auto-completion in pyCharm ;-)
