### ISSUE TITLE
Refactoring proposal on pop-up dialogs

### ISSUE THREAD

**Issue by vtexier** [ucoin-io/sakia#317]
I wanted to add the wot refresh after a successfully sent certification.
The easy way was to add it in the certify method in the wot_tab.
But certification can be done elsewhere and wot.refresh() should be done as well in this case.

So I tried to add a signal/slot system between the dialog and the wot.refresh().
But the dialog is created on-the-fly and destroyed without the possibility to declare signal/slot.

I propose to re-factor the code to be able to connect dialog signals with various slots from the main_window. To achieve this, I think that dialogs need to be created hidden, then showed/hidden as needed, and never destroyed.

**Comment by Insoleet** [comment]
Maybe we could simply add a signal in the account class and connect views to this class ? 

Generally, views are really hard to test and maintain. I'd prefer if we could add more logic in the core classes and the less possible in the GUI !

**Comment by vtexier** [comment]
Yes you're right !
Ok, done as you say in  ceb8664.
I will look at the test framework to see if I can write the certify test myself...

**Comment by Insoleet** [comment]
Please take example on the new unit test written in the branch feature/explorer_tab !

**Comment by vtexier** [comment]
Too hard for me, sorry... ;-( 
I leave the test to you @Insoleet

**Comment by Insoleet** [comment]
No problem :) thanks for tonight commits ! Release coming soon ! :D

**Comment by Insoleet** [comment]
Test added !
