### ISSUE TITLE
Configure account dialog does not refresh tiles view

### ISSUE THREAD

**Issue by Samsemilio** [ucoin-io/sakia#319]
I just accidentally added the meta brouzouf accidentally twice. Is there a way to remove it again at the moment? 
![bildschirmfoto 2015-12-27 um 11 26 33](https://cloud.githubusercontent.com/assets/747161/12009878/b4b03a5e-ac8c-11e5-9a6a-21eb655479ae.png)

**Comment by Insoleet** [comment]
Yes, in the menu Configure your account, you can add and remove currencies !

**Comment by Samsemilio** [comment]
aha, merci!! :)

**Comment by Samsemilio** [comment]
In order fr the ui to reflect the new setting, you will have to restart sakia

**Comment by Insoleet** [comment]
I could not reproduce this behaviour. Do you remember exactly what did you do ?

**Comment by Samsemilio** [comment]
no sorry, I have a brain like a mouse :D

**Comment by Insoleet** [comment]
Can you try to reproduce it then ?

**Comment by Samsemilio** [comment]
Not reproducable by me either.
