### ISSUE TITLE
Automatically sort contact list by name

### ISSUE THREAD

**Issue by Samsemilio** [ucoin-io/sakia#323]

**Comment by Insoleet** [comment]
Where exactly ? Can you put a screenshot?

**Comment by Samsemilio** [comment]
The dropdown when sending money or certifying a person. 
![bildschirmfoto 2015-12-27 um 14 45 09](https://cloud.githubusercontent.com/assets/747161/12010469/811b3704-aca8-11e5-8d4d-139b45cea199.png)
