### ISSUE TITLE
Sakia crash when publishing ID with utf8

### ISSUE THREAD

**Issue by galuel** [ucoin-io/sakia#331]
Sakia crashes when clicking "publish ID" for a new ID : ğaluel

No information in the terminal.

**Comment by M5oul** [comment]
uid could only be in ASCII:
When trying publishing a new identity with `ğ` character, I get this message:
`'ascii' codec can't encode character '\u011f' in position 4: ordinal not in range (128)'.

**Comment by Insoleet** [comment]
@c-geek  : only ASCII, special character too ? (like, are chars ( ) [] - ... authorized ?)

**Comment by c-geek** [comment]
It is not written explicitely in the protocol, however I only allow alphanumeric characters: https://github.com/ucoin-io/ucoin/blob/master/app/lib/constants.js#L6
