### ISSUE TITLE
Add a disclaimer about certifications

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#332]
On the very first certification in Sakia, it could be very nice to have a warning dialog of confirmation with the following content:

> 1.) Don't certify an account if you believe the issuers identity might be faked.
> 2.) Don't certify an account if you believe the issuer already has another certified account.
> 3.) Don't certify an account if you believe the issuer purposely or carelessly violates rule 1 or 2 (the issuer certifies faked or double accounts)

**Comment by Insoleet** [comment]
Good idea.
