### ISSUE TITLE
Relative Z-sum

### ISSUE THREAD

**Issue by galuel** [ucoin-io/sakia#335]
In the Relative Z-sum I can see -11 R0 UD I don't understand : 

- How can I be less than 10 UD !?
- I produced yet my first UD, so I should be at 9 UD
- I should see -9 UD and not R0 UD. (The name of the money I check is written yet up left, it's ok)

**Comment by M5oul** [comment]
I actually own 15,53 UD MB because of big growth number of members, that could explain you have this results.

**Comment by galuel** [comment]
No it cannot, it's not coherent. I can see in information tab M/N = 10 UD, and I own 1 UD and 1 UD - 10 UD = -9 UD I cannot see nothing to explain another result for 1-10

**Comment by M5oul** [comment]
I own 15,53 UD MB and 4,53 R0 MB. Their must be an issue.

**Comment by Insoleet** [comment]
Did you try to do the calculations based on what you see in the information tab, to check ?

**Comment by galuel** [comment]
I cannot undersand anything because my account shows 6,956063 PMB and the UD(t) is 6 893 396 145 905 682 MB, and I don't know what is "PMB" compared to "MB".

Unclear...

**Comment by Insoleet** [comment]
P is Peta. You can disable scientific units in the parameters.

**Comment by galuel** [comment]
Ok (preferences is not clear, because international units work with 10^5, not at all with "P" see scientific calculator in your computer), I give number information without the 12 last digits : 

Account : 6 956 units
UD(t) : 6 893 units
M(t-1)/N(t) : 68 933

RZ should be with thoses values : (6 956 - 68 933) / 6893 = -8,99 UD

But I see : -9,99

QZ also seem false, I see : -68 871

But it should be : 6956 - 68933 = -61 977

Whatever you choose to make calculation, the user should be able to make the calculation too and obtain the same result. One of the problems I can see is that "t" and "t+1" are not defined in the information tab, neither the information calculation used to obtain the 4 referentials, so the user cannot verify.

One important information is that N(t) will change between "t" and "t+1", and so UD(t+1) will be sure the good value only when the blockchain time = t+1, not before and not after. So you must choose the definition of the current-time you use to make calculation : is it "t", is it "current time" !?, it's not clear.

Then when it is chosen, it's important the user can see the data, and can control them through its account, and of course control also the data through what exist in the blockchain, and obtain the same results he can see in the screen.

The notation of units, DU, Q0 MB and RO MB is heavy and not necessary, so I suggest : 

- Put somewhere in the same line or in a box, always visible, the name of the currency, the referential chosen, and a "?" button to obtain information about the referential chosen (how it is calculated, and a little explanation of why it is calculated like this, for instance for R0 : "in this referential the sum of all the accounts will always be 0, because we subtract the average to all).
- Because money name, and referential, and information will be always visible, we can output the referential/units after the numbers, and it will be lighter to read.
- Hour and minutes should be good to add instead of only the day in the transactions list.
- When I created the account ğaluel it seemed to bug with problem of ASCII, but I can see ğaluel UD transactions (coming from ğaluel) in Sakia, from 05/01 and 06/01 dates + un mix with a cgeek transaction, in ğaluel and galuelien account... I deleted the ğaluel account, I don't know more.

**Comment by Insoleet** [comment]
@vtexier : Can you look at the points made by Galuel about the informations tab ?

**Comment by vtexier** [comment]
@Insoleet argh, I spend the morning fixing many problems, and my push is rejected because you have done the same in between. Faster than me as always...

Please don't do anything more here, I have three commits to push.
I will resolve conflicts.

**Comment by vtexier** [comment]
Fix wrong ZSUM values calculation in 067f29649b085aaf627f4052ff175087dfbfee2a
Fix units name displayed for differential values in ZSUM referentials in 8eaec0a0f2858dfb0b1cc9e1808c0bd1ca8a0638
Add datetime for penultimate UD (t-1) in informations_tab in 645f4cd4a5e4fe665ae4c3178e413a953971ac35

Todo : 
* Fix scientific display not working in informations_tab
* Display referentials formulae in informations_tab or elsewhere

**Comment by Insoleet** [comment]
Ahah ok, next time assign the task to you ^^

Thanks for these fixes :+1:

**Comment by Insoleet** [comment]
Ok I fixed the units in the informations tab so that I could release a fix for 0.13 ucoin nodes.
Referentials formulae should come with 0.12 version as it's an *enhancement* and not a bug fix.

**Comment by vtexier** [comment]
Display all referential help in information tab.
It is dynamic, so no need to update the tab when adding a referential !

**Comment by Insoleet** [comment]
I see this in my Transactions tab : 

![screenshot_20160131_114843](https://cloud.githubusercontent.com/assets/1170293/12701665/9983a938-c810-11e5-977d-c06714470ec8.png)

**Comment by vtexier** [comment]
Apparently, the change from @classmethod to @property make it impossible to refer to it from the class as before. Need to create an instance.

**Comment by Insoleet** [comment]
Ok. I'm not sure to understand, what is wrong in txhistory model ?

```python

    def headerData(self, section, orientation, role):
        if self.account and self.community:
            if role == Qt.DisplayRole:
                if self.columns_types[section] == 'payment' or self.columns_types[section] == 'deposit':
                    return '{:}\n({:})'.format(
                        self.column_headers[section](),
                        self.account.current_ref(0, self.community, self.app, None).diff_units
                    )

                return self.column_headers[section]()
```

**Comment by vtexier** [comment]
it is not here. It is in the Quantitative class : 

```python
    @property
    def diff_units(self):
        return Quantitative.units
```

if you replace by self.units, it works !

and here in RelativeZSum class: 

```python
    @property
    def diff_units(self):
        return Relative.units
```

Harder to solve here.
RelativeZSum is a subset of Relative referential, so it should display Relative.units.
It worked when Relative.units was a `@classmethod` type, not a `@property` type...

**Comment by Insoleet** [comment]
I'm not sure if it's worth making a property if it duplicates the code. Why do you need it to be a property ?

**Comment by vtexier** [comment]
You change classmethod to property yourself here 8c4990af09b9ce8b535e003c2d8fae23c9f963e3.
So the bug was already here before my merge I believe  😊

**Comment by Insoleet** [comment]
Well, weird You are probably right but I wonder why we never saw it. I fixed it anyway !
