### ISSUE TITLE
No UD transactions are displayed since 2016

### ISSUE THREAD

**Issue by Arcurus** [ucoin-io/sakia#339]
it seems that i (Arcurus)  didnt receive any ud since 2016.

is it a ucoin or a sakia / display bug?

or is it something else?

it could also be that generally no transactions since 2016 are displayed. sakia chrashed when i tried to make an transaction see other bug, so i couldnt test it if it is a general problem.

**Comment by Insoleet** [comment]
We will check what is happening. Could be linked to some changes @c-geek made with 0.13 version.

**Comment by Insoleet** [comment]
Fixing the memberships seems to have fixed this bugs. I can see all my UDs from 2016.
