### ISSUE TITLE
Network automatic refresh: prefer websockets

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#345]
For historical reasons Sakia *pulls* the blocks from the network, but from ucoin@0.12 at least we can use websockets for *pushing* blocks to Sakia.

Cesium uses it today and it works very well, I get almost instantly noticed about new blocks from the peers:

![image](https://cloud.githubusercontent.com/assets/969136/12262457/69b2101a-b928-11e5-8d5e-60040a756ea6.png)

**Comment by c-geek** [comment]
The API is defined here: https://github.com/ucoin-io/ucoin/blob/master/doc/HTTP_API.md#websocket

**Comment by Insoleet** [comment]
I want to do it for 0.12. I'll see if it's possible. Maybe some other feature will be postponed to 0.13.

**Comment by Insoleet** [comment]
Done !

**Comment by c-geek** [comment]
Mouhaha can't want to see it :-)

**Comment by c-geek** [comment]
Have you tested it over time? Do websocket close after, say, 1hour?

For Cesium it happens after few minutes. I have to reconnect to keep the connection alive (there is probably a better way, like ping/pong, but I havn't dug this yet).

**Comment by Insoleet** [comment]
I don't know. The nodes are refreshed reguarly with the following algorithm : 
 - Every 15 seconds, refresh next node
 - If node is not connected via ws, connect via ws
 - If it fails, refresh via HTTP GET

So if the ws fails, the node will try to reconnect later.
