### ISSUE TITLE
Add a clear indicator telling us if we are member or not

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#352]
It seems I was no more a member since 10 days, but did not notice it.

Maybe Sakia could help us in some way?

**Comment by Insoleet** [comment]
In the home view, the tile shows if you are a member or not.

Sakia also sends notifications + writes on the bottom of the window when you are going to expire soon. (2/3 of your membership was consumed)

Any thing Sakia could do differently / better ?

**Comment by c-geek** [comment]
Did not notice the Home indicator, maybe because it was just text and felt like it did not require my attention.

Maybe a colored icon would be better instead of text? And maybe add this icon in the main view when we clicked in a currency.

This is just suggestion.

**Comment by c-geek** [comment]
Actually it has been only few hours, and not 10 days.

Also maybe we do not need an icon on the home, but just the Non-Member label to be colored:

* red if we are not a member
* orange if we are about to be kicked
* green if we are a member

**Comment by Insoleet** [comment]
Ok for your last proposal. Kind of easy to do ! :+1: 

@vtexier , maybe you want to do it ?

**Comment by vtexier** [comment]
Ok I take it.
