### ISSUE TITLE
Network tab is full of grey

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#362]
After some waiting, I got the following screen:

![image](https://cloud.githubusercontent.com/assets/969136/12759420/4c1e4176-c9e1-11e5-874f-708595219314.png)

And if I manually refresh the network, all becomes green again:

![image](https://cloud.githubusercontent.com/assets/969136/12759444/69c1d396-c9e1-11e5-831d-276babc444dd.png)

And just right now, all nodes updated in just 1-2 seconds to this:

![image](https://cloud.githubusercontent.com/assets/969136/12759499/b280d9ba-c9e1-11e5-95dd-2a9d8648193b.png)

I first thought, as said on the chatroom, that is was a uoin@0.14.0 issue, but obvously it also happens with 0.14.2 nodes.

**Comment by Insoleet** [comment]
I fixed some of the grey errors in latest ucoinpy update but some remains because of ucoin nodes in 0.14.0 I think.
