### ISSUE TITLE
Prefix with big amount of units

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#372]
Could we display 10¹⁵, 10¹⁸ instead of P, E which I don't remember what does it mean.
I need to display [IS prefix](https://fr.wikipedia.org/wiki/Pr%C3%A9fixes_du_syst%C3%A8me_international_d'unit%C3%A9s) to know at what it correspond.

We have habit with K, M, G, T. But P, E are used a little bit.
May be, it could display an abbreviation _10¹⁸_ and/or _Exa_ for _E_.

It could be choose in configuration.

**Comment by Insoleet** [comment]
OK to write Peta and Exa instead of P/E.
