### ISSUE TITLE
Can't right click my identity on WoT tab

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/sakia#376]

**Comment by Insoleet** [comment]
I think it's on purpose but I can't find the issue explaining why... 

```python

    def contextMenuEvent(self, event: QGraphicsSceneContextMenuEvent):
        """
        Right click on node to show node menu
        Except on wallet node

        :param event: scene context menu event
        """
        #  no menu on the wallet node
        if self.status_wallet:
            return None
        self.scene().node_context_menu_requested.emit(self.id)

```

@vtexier maybe ?

**Comment by vtexier** [comment]
It was to avoid weird things as auto certifications I think. But I find this limitation frustrating as well.

I will look at it to re-activate a context menu with only actions authorized on our own identity. Asap.

**Comment by vtexier** [comment]
@Insoleet : there seems to be no easy way to know if the identity param passed to the context menu is the account identity... It is required to hide some menus like "certify", "add as contact", when having the context menu on our own identity.
To get the account identity, I need to use async...

**Comment by Insoleet** [comment]
The context menu has access to the account so I think you can just compare to the account.identity() property !

**Comment by vtexier** [comment]
I tried this : 

`if menu._account.identity(menu._community) != identity: `

I get : 
   

 ` context_menu.py:46: RuntimeWarning: coroutine 'Account.identity' was never awaited`

So identity() method is an async method...

But impossible to use await in the context menu static method, pyCharm complains...

**Comment by Insoleet** [comment]
Ok, maybe easier : use account.pubkey to compare to the identity.pubkey
