### ISSUE TITLE
Erreur sur un Windows Xp

### ISSUE THREAD

**Issue by vincentux** [ucoin-io/sakia#396]
Message d'erreur au lancement de Sakia sur un windows XP 32 bits 

"Le point d'entrée de procédure GetFinalPathNameByHandleW est introuvable dans la bibliothèque de liaison dynamique KERNELL32.dll"

**Comment by Insoleet** [comment]
Ah c'est sur Windows XP... Je ne vais pas pouvoir supporter cet environnement malheuresement. Il va falloir migrer à une version plus récente ! (ou passer à Linux ;) )

**Comment by vincentux** [comment]
Pas de souci, chez moi ça fonctionne très bien (Linux bien sur) 
là le pc est celui du boulot (mais passage a windows 7 prévu bientôt).
