### ISSUE TITLE
Message au démarrage

### ISSUE THREAD

**Issue by vincentux** [ucoin-io/sakia#401]
Au lancement de l'application j'ai le message suivant dans le terminal (mais rien de bloquant) ...

`
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled`

_Config : x86_64 Linux 4.4.6-1-MANJARO
Sakia Version 0.20.0dev3_

**Comment by Insoleet** [comment]
Yes, this is linked to this bug : https://github.com/ucoin-io/sakia/issues/399
