### ISSUE TITLE
Have 3 times the same currency for tiles

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#405]
This happened when I tried to add a node to init my account, I made "enter" but as it did not respond, I made several "enter" and even if everything seemed OK with one node added, after the final password asking Sakia crashed.

Which lead to this:

![image](https://cloud.githubusercontent.com/assets/969136/14467075/f2470bc6-00d9-11e6-9367-e71679e56f78.png)

**Comment by Insoleet** [comment]
In Account > Configure, do you have 3 times the community ?

**Comment by c-geek** [comment]
Sorry I've deleted my folder, and with your tip on #397 I can't reproduce this issue.

**Comment by M5oul** [comment]
I reproduce it many times.
I thought it was feature :smirk_cat:
