### ISSUE TITLE
Network discovering?

### ISSUE THREAD

**Issue by c-geek** [ucoin-io/sakia#406]
It seems the network is no more discovered by Sakia:

![image](https://cloud.githubusercontent.com/assets/969136/14470659/1039d06c-00eb-11e6-8219-276f429ab109.png)

However this node knows at least 3 other nodes UP:

![image](https://cloud.githubusercontent.com/assets/969136/14470702/4c63979e-00eb-11e6-8d04-a6fb9a35961a.png)

You can check the URLs:

* http://twiced.fr:9330/network/peering/peers?leaves=true
* http://twiced.fr:9330/network/peering/peers?leaf=3073427178784BCD542948C426C21635ECF00BEE921B1AE52756ACE46A51A81B

```

{
  "depth": 2,
  "nodesCount": 3,
  "leavesCount": 4,
  "root": "894AADAA94940632F7672858F0DFBDF0DABA817317652CC76AA0265C37774C82",
  "leaves": [],
  "leaf": {
    "hash": "3073427178784BCD542948C426C21635ECF00BEE921B1AE52756ACE46A51A81B",
    "value": {
      "version": 2,
      "currency": "super_currency",
      "endpoints": [
        "BASIC_MERKLED_API testnet.duniter.inso.ovh 80"
      ],
      "status": "UP",
      "block": "30466-0025446ECCF7184E905DBFA2AD68A03DFF6608E9A7CA78D182F8EF2E5A2B5FDF",
      "signature": "+3VsNyE4LctGPIzMBXmt/LrJuskSXbP/3X6n8/TwaeRbpXV0o03veZEF0qTTBjcXEHad++B7Cnc6jppWdjtPCA==",
      "raw": "Version: 2\nType: Peer\nCurrency: super_currency\nPublicKey: 8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU\nBlock: 30466-0025446ECCF7184E905DBFA2AD68A03DFF6608E9A7CA78D182F8EF2E5A2B5FDF\nEndpoints:\nBASIC_MERKLED_API testnet.duniter.inso.ovh 80\n",
      "pubkey": "8Fi1VSTbjkXguwThF4v2ZxC5whK7pwG2vcGTkPUPjPGU",
      "first_down": 0,
      "last_try": 0
    }
  }
}
```

**Comment by Insoleet** [comment]
Since websockets, network is discovered only when peers are broadcasted. Maybe the nodes are not broadcasting any new peer ?

**Comment by c-geek** [comment]
OK, added ucoin-io/ucoin#384.

**Comment by c-geek** [comment]
Confirmed bug from Duniter.
